/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as TenantsIndexRouteImport } from './routes/tenants.index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as UsersAddRouteImport } from './routes/users_.add'
import { Route as TenantsAddRouteImport } from './routes/tenants_.add'
import { Route as RoomsAddRouteImport } from './routes/rooms_.add'
import { Route as PosSalesRouteImport } from './routes/pos.sales'
import { Route as PosProductsRouteImport } from './routes/pos.products'
import { Route as PosDashboardRouteImport } from './routes/pos.dashboard'
import { Route as PosCategoriesRouteImport } from './routes/pos.categories'
import { Route as PaymentsAddRouteImport } from './routes/payments_.add'
import { Route as MaintenanceAddRouteImport } from './routes/maintenance_.add'
import { Route as ExpensesAddRouteImport } from './routes/expenses_.add'
import { Route as BookingsAddRouteImport } from './routes/bookings_.add'
import { Route as UsersEditUserIdRouteImport } from './routes/users_.edit.$userId'
import { Route as TenantsEditTenantIdRouteImport } from './routes/tenants_.edit.$tenantId'
import { Route as RoomsEditRoomIdRouteImport } from './routes/rooms_.edit.$roomId'
import { Route as PaymentsEditPaymentIdRouteImport } from './routes/payments_.edit.$paymentId'
import { Route as MaintenanceEditMaintenanceIdRouteImport } from './routes/maintenance_.edit.$maintenanceId'
import { Route as ExpensesEditExpenseIdRouteImport } from './routes/expenses_.edit.$expenseId'
import { Route as BookingsEditBookingIdRouteImport } from './routes/bookings_.edit.$bookingId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersAddRoute = UsersAddRouteImport.update({
  id: '/users_/add',
  path: '/users/add',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsAddRoute = TenantsAddRouteImport.update({
  id: '/tenants_/add',
  path: '/tenants/add',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsAddRoute = RoomsAddRouteImport.update({
  id: '/rooms_/add',
  path: '/rooms/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PosSalesRoute = PosSalesRouteImport.update({
  id: '/pos/sales',
  path: '/pos/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const PosProductsRoute = PosProductsRouteImport.update({
  id: '/pos/products',
  path: '/pos/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PosDashboardRoute = PosDashboardRouteImport.update({
  id: '/pos/dashboard',
  path: '/pos/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PosCategoriesRoute = PosCategoriesRouteImport.update({
  id: '/pos/categories',
  path: '/pos/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsAddRoute = PaymentsAddRouteImport.update({
  id: '/payments_/add',
  path: '/payments/add',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceAddRoute = MaintenanceAddRouteImport.update({
  id: '/maintenance_/add',
  path: '/maintenance/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesAddRoute = ExpensesAddRouteImport.update({
  id: '/expenses_/add',
  path: '/expenses/add',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsAddRoute = BookingsAddRouteImport.update({
  id: '/bookings_/add',
  path: '/bookings/add',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersEditUserIdRoute = UsersEditUserIdRouteImport.update({
  id: '/users_/edit/$userId',
  path: '/users/edit/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsEditTenantIdRoute = TenantsEditTenantIdRouteImport.update({
  id: '/tenants_/edit/$tenantId',
  path: '/tenants/edit/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsEditRoomIdRoute = RoomsEditRoomIdRouteImport.update({
  id: '/rooms_/edit/$roomId',
  path: '/rooms/edit/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsEditPaymentIdRoute = PaymentsEditPaymentIdRouteImport.update({
  id: '/payments_/edit/$paymentId',
  path: '/payments/edit/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceEditMaintenanceIdRoute =
  MaintenanceEditMaintenanceIdRouteImport.update({
    id: '/maintenance_/edit/$maintenanceId',
    path: '/maintenance/edit/$maintenanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExpensesEditExpenseIdRoute = ExpensesEditExpenseIdRouteImport.update({
  id: '/expenses_/edit/$expenseId',
  path: '/expenses/edit/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsEditBookingIdRoute = BookingsEditBookingIdRouteImport.update({
  id: '/bookings_/edit/$bookingId',
  path: '/bookings/edit/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/bookings/add': typeof BookingsAddRoute
  '/expenses/add': typeof ExpensesAddRoute
  '/maintenance/add': typeof MaintenanceAddRoute
  '/payments/add': typeof PaymentsAddRoute
  '/pos/categories': typeof PosCategoriesRoute
  '/pos/dashboard': typeof PosDashboardRoute
  '/pos/products': typeof PosProductsRoute
  '/pos/sales': typeof PosSalesRoute
  '/rooms/add': typeof RoomsAddRoute
  '/tenants/add': typeof TenantsAddRoute
  '/users/add': typeof UsersAddRoute
  '/bookings/': typeof BookingsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/bookings/edit/$bookingId': typeof BookingsEditBookingIdRoute
  '/expenses/edit/$expenseId': typeof ExpensesEditExpenseIdRoute
  '/maintenance/edit/$maintenanceId': typeof MaintenanceEditMaintenanceIdRoute
  '/payments/edit/$paymentId': typeof PaymentsEditPaymentIdRoute
  '/rooms/edit/$roomId': typeof RoomsEditRoomIdRoute
  '/tenants/edit/$tenantId': typeof TenantsEditTenantIdRoute
  '/users/edit/$userId': typeof UsersEditUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/bookings/add': typeof BookingsAddRoute
  '/expenses/add': typeof ExpensesAddRoute
  '/maintenance/add': typeof MaintenanceAddRoute
  '/payments/add': typeof PaymentsAddRoute
  '/pos/categories': typeof PosCategoriesRoute
  '/pos/dashboard': typeof PosDashboardRoute
  '/pos/products': typeof PosProductsRoute
  '/pos/sales': typeof PosSalesRoute
  '/rooms/add': typeof RoomsAddRoute
  '/tenants/add': typeof TenantsAddRoute
  '/users/add': typeof UsersAddRoute
  '/bookings': typeof BookingsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/users': typeof UsersIndexRoute
  '/bookings/edit/$bookingId': typeof BookingsEditBookingIdRoute
  '/expenses/edit/$expenseId': typeof ExpensesEditExpenseIdRoute
  '/maintenance/edit/$maintenanceId': typeof MaintenanceEditMaintenanceIdRoute
  '/payments/edit/$paymentId': typeof PaymentsEditPaymentIdRoute
  '/rooms/edit/$roomId': typeof RoomsEditRoomIdRoute
  '/tenants/edit/$tenantId': typeof TenantsEditTenantIdRoute
  '/users/edit/$userId': typeof UsersEditUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/bookings_/add': typeof BookingsAddRoute
  '/expenses_/add': typeof ExpensesAddRoute
  '/maintenance_/add': typeof MaintenanceAddRoute
  '/payments_/add': typeof PaymentsAddRoute
  '/pos/categories': typeof PosCategoriesRoute
  '/pos/dashboard': typeof PosDashboardRoute
  '/pos/products': typeof PosProductsRoute
  '/pos/sales': typeof PosSalesRoute
  '/rooms_/add': typeof RoomsAddRoute
  '/tenants_/add': typeof TenantsAddRoute
  '/users_/add': typeof UsersAddRoute
  '/bookings/': typeof BookingsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/bookings_/edit/$bookingId': typeof BookingsEditBookingIdRoute
  '/expenses_/edit/$expenseId': typeof ExpensesEditExpenseIdRoute
  '/maintenance_/edit/$maintenanceId': typeof MaintenanceEditMaintenanceIdRoute
  '/payments_/edit/$paymentId': typeof PaymentsEditPaymentIdRoute
  '/rooms_/edit/$roomId': typeof RoomsEditRoomIdRoute
  '/tenants_/edit/$tenantId': typeof TenantsEditTenantIdRoute
  '/users_/edit/$userId': typeof UsersEditUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/calendar'
    | '/contact'
    | '/dashboard'
    | '/documents'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reports'
    | '/security'
    | '/services'
    | '/settings'
    | '/bookings/add'
    | '/expenses/add'
    | '/maintenance/add'
    | '/payments/add'
    | '/pos/categories'
    | '/pos/dashboard'
    | '/pos/products'
    | '/pos/sales'
    | '/rooms/add'
    | '/tenants/add'
    | '/users/add'
    | '/bookings/'
    | '/categories/'
    | '/expenses/'
    | '/invoices/'
    | '/maintenance/'
    | '/payments/'
    | '/rooms/'
    | '/tenants/'
    | '/users/'
    | '/bookings/edit/$bookingId'
    | '/expenses/edit/$expenseId'
    | '/maintenance/edit/$maintenanceId'
    | '/payments/edit/$paymentId'
    | '/rooms/edit/$roomId'
    | '/tenants/edit/$tenantId'
    | '/users/edit/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/calendar'
    | '/contact'
    | '/dashboard'
    | '/documents'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reports'
    | '/security'
    | '/services'
    | '/settings'
    | '/bookings/add'
    | '/expenses/add'
    | '/maintenance/add'
    | '/payments/add'
    | '/pos/categories'
    | '/pos/dashboard'
    | '/pos/products'
    | '/pos/sales'
    | '/rooms/add'
    | '/tenants/add'
    | '/users/add'
    | '/bookings'
    | '/categories'
    | '/expenses'
    | '/invoices'
    | '/maintenance'
    | '/payments'
    | '/rooms'
    | '/tenants'
    | '/users'
    | '/bookings/edit/$bookingId'
    | '/expenses/edit/$expenseId'
    | '/maintenance/edit/$maintenanceId'
    | '/payments/edit/$paymentId'
    | '/rooms/edit/$roomId'
    | '/tenants/edit/$tenantId'
    | '/users/edit/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/calendar'
    | '/contact'
    | '/dashboard'
    | '/documents'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/reports'
    | '/security'
    | '/services'
    | '/settings'
    | '/bookings_/add'
    | '/expenses_/add'
    | '/maintenance_/add'
    | '/payments_/add'
    | '/pos/categories'
    | '/pos/dashboard'
    | '/pos/products'
    | '/pos/sales'
    | '/rooms_/add'
    | '/tenants_/add'
    | '/users_/add'
    | '/bookings/'
    | '/categories/'
    | '/expenses/'
    | '/invoices/'
    | '/maintenance/'
    | '/payments/'
    | '/rooms/'
    | '/tenants/'
    | '/users/'
    | '/bookings_/edit/$bookingId'
    | '/expenses_/edit/$expenseId'
    | '/maintenance_/edit/$maintenanceId'
    | '/payments_/edit/$paymentId'
    | '/rooms_/edit/$roomId'
    | '/tenants_/edit/$tenantId'
    | '/users_/edit/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  BookingsAddRoute: typeof BookingsAddRoute
  ExpensesAddRoute: typeof ExpensesAddRoute
  MaintenanceAddRoute: typeof MaintenanceAddRoute
  PaymentsAddRoute: typeof PaymentsAddRoute
  PosCategoriesRoute: typeof PosCategoriesRoute
  PosDashboardRoute: typeof PosDashboardRoute
  PosProductsRoute: typeof PosProductsRoute
  PosSalesRoute: typeof PosSalesRoute
  RoomsAddRoute: typeof RoomsAddRoute
  TenantsAddRoute: typeof TenantsAddRoute
  UsersAddRoute: typeof UsersAddRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  BookingsEditBookingIdRoute: typeof BookingsEditBookingIdRoute
  ExpensesEditExpenseIdRoute: typeof ExpensesEditExpenseIdRoute
  MaintenanceEditMaintenanceIdRoute: typeof MaintenanceEditMaintenanceIdRoute
  PaymentsEditPaymentIdRoute: typeof PaymentsEditPaymentIdRoute
  RoomsEditRoomIdRoute: typeof RoomsEditRoomIdRoute
  TenantsEditTenantIdRoute: typeof TenantsEditTenantIdRoute
  UsersEditUserIdRoute: typeof UsersEditUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/add': {
      id: '/users_/add'
      path: '/users/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof UsersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants_/add': {
      id: '/tenants_/add'
      path: '/tenants/add'
      fullPath: '/tenants/add'
      preLoaderRoute: typeof TenantsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms_/add': {
      id: '/rooms_/add'
      path: '/rooms/add'
      fullPath: '/rooms/add'
      preLoaderRoute: typeof RoomsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/sales': {
      id: '/pos/sales'
      path: '/pos/sales'
      fullPath: '/pos/sales'
      preLoaderRoute: typeof PosSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/products': {
      id: '/pos/products'
      path: '/pos/products'
      fullPath: '/pos/products'
      preLoaderRoute: typeof PosProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/dashboard': {
      id: '/pos/dashboard'
      path: '/pos/dashboard'
      fullPath: '/pos/dashboard'
      preLoaderRoute: typeof PosDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/categories': {
      id: '/pos/categories'
      path: '/pos/categories'
      fullPath: '/pos/categories'
      preLoaderRoute: typeof PosCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments_/add': {
      id: '/payments_/add'
      path: '/payments/add'
      fullPath: '/payments/add'
      preLoaderRoute: typeof PaymentsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance_/add': {
      id: '/maintenance_/add'
      path: '/maintenance/add'
      fullPath: '/maintenance/add'
      preLoaderRoute: typeof MaintenanceAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses_/add': {
      id: '/expenses_/add'
      path: '/expenses/add'
      fullPath: '/expenses/add'
      preLoaderRoute: typeof ExpensesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings_/add': {
      id: '/bookings_/add'
      path: '/bookings/add'
      fullPath: '/bookings/add'
      preLoaderRoute: typeof BookingsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/edit/$userId': {
      id: '/users_/edit/$userId'
      path: '/users/edit/$userId'
      fullPath: '/users/edit/$userId'
      preLoaderRoute: typeof UsersEditUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants_/edit/$tenantId': {
      id: '/tenants_/edit/$tenantId'
      path: '/tenants/edit/$tenantId'
      fullPath: '/tenants/edit/$tenantId'
      preLoaderRoute: typeof TenantsEditTenantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms_/edit/$roomId': {
      id: '/rooms_/edit/$roomId'
      path: '/rooms/edit/$roomId'
      fullPath: '/rooms/edit/$roomId'
      preLoaderRoute: typeof RoomsEditRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments_/edit/$paymentId': {
      id: '/payments_/edit/$paymentId'
      path: '/payments/edit/$paymentId'
      fullPath: '/payments/edit/$paymentId'
      preLoaderRoute: typeof PaymentsEditPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance_/edit/$maintenanceId': {
      id: '/maintenance_/edit/$maintenanceId'
      path: '/maintenance/edit/$maintenanceId'
      fullPath: '/maintenance/edit/$maintenanceId'
      preLoaderRoute: typeof MaintenanceEditMaintenanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses_/edit/$expenseId': {
      id: '/expenses_/edit/$expenseId'
      path: '/expenses/edit/$expenseId'
      fullPath: '/expenses/edit/$expenseId'
      preLoaderRoute: typeof ExpensesEditExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings_/edit/$bookingId': {
      id: '/bookings_/edit/$bookingId'
      path: '/bookings/edit/$bookingId'
      fullPath: '/bookings/edit/$bookingId'
      preLoaderRoute: typeof BookingsEditBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  BookingsAddRoute: BookingsAddRoute,
  ExpensesAddRoute: ExpensesAddRoute,
  MaintenanceAddRoute: MaintenanceAddRoute,
  PaymentsAddRoute: PaymentsAddRoute,
  PosCategoriesRoute: PosCategoriesRoute,
  PosDashboardRoute: PosDashboardRoute,
  PosProductsRoute: PosProductsRoute,
  PosSalesRoute: PosSalesRoute,
  RoomsAddRoute: RoomsAddRoute,
  TenantsAddRoute: TenantsAddRoute,
  UsersAddRoute: UsersAddRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  BookingsEditBookingIdRoute: BookingsEditBookingIdRoute,
  ExpensesEditExpenseIdRoute: ExpensesEditExpenseIdRoute,
  MaintenanceEditMaintenanceIdRoute: MaintenanceEditMaintenanceIdRoute,
  PaymentsEditPaymentIdRoute: PaymentsEditPaymentIdRoute,
  RoomsEditRoomIdRoute: RoomsEditRoomIdRoute,
  TenantsEditTenantIdRoute: TenantsEditTenantIdRoute,
  UsersEditUserIdRoute: UsersEditUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
